# Generated by Django 2.2.28 on 2026-06-13 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('language', models.CharField(blank=True, choices=[('af', 'AF'), ('ar', 'AR'), ('ast', 'AST'), ('az', 'AZ'), ('bg', 'BG'), ('be', 'BE'), ('bn', 'BN'), ('br', 'BR'), ('bs', 'BS'), ('ca', 'CA'), ('cs', 'CS'), ('cy', 'CY'), ('da', 'DA'), ('de', 'DE'), ('dsb', 'DSB'), ('el', 'EL'), ('en', 'EN'), ('en-au', 'EN-AU'), ('en-gb', 'EN-GB'), ('eo', 'EO'), ('es', 'ES'), ('es-ar', 'ES-AR'), ('es-co', 'ES-CO'), ('es-mx', 'ES-MX'), ('es-ni', 'ES-NI'), ('es-ve', 'ES-VE'), ('et', 'ET'), ('eu', 'EU'), ('fa', 'FA'), ('fi', 'FI'), ('fr', 'FR'), ('fy', 'FY'), ('ga', 'GA'), ('gd', 'GD'), ('gl', 'GL'), ('he', 'HE'), ('hi', 'HI'), ('hr', 'HR'), ('hsb', 'HSB'), ('hu', 'HU'), ('hy', 'HY'), ('ia', 'IA'), ('id', 'ID'), ('io', 'IO'), ('is', 'IS'), ('it', 'IT'), ('ja', 'JA'), ('ka', 'KA'), ('kab', 'KAB'), ('kk', 'KK'), ('km', 'KM'), ('kn', 'KN'), ('ko', 'KO'), ('lb', 'LB'), ('lt', 'LT'), ('lv', 'LV'), ('mk', 'MK'), ('ml', 'ML'), ('mn', 'MN'), ('mr', 'MR'), ('my', 'MY'), ('nb', 'NB'), ('ne', 'NE'), ('nl', 'NL'), ('nn', 'NN'), ('os', 'OS'), ('pa', 'PA'), ('pl', 'PL'), ('pt', 'PT'), ('pt-br', 'PT-BR'), ('ro', 'RO'), ('ru', 'RU'), ('sk', 'SK'), ('sl', 'SL'), ('sq', 'SQ'), ('sr', 'SR'), ('sr-latn', 'SR-LATN'), ('sv', 'SV'), ('sw', 'SW'), ('ta', 'TA'), ('te', 'TE'), ('th', 'TH'), ('tr', 'TR'), ('tt', 'TT'), ('udm', 'UDM'), ('uk', 'UK'), ('ur', 'UR'), ('vi', 'VI'), ('zh-hans', 'ZH-HANS'), ('zh-hant', 'ZH-HANT')], default=None, max_length=8, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
