# Generated by Django 2.2.28 on 2026-06-13 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0010_auto_20210311_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCheckTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=16)),
                ('total_pins', models.IntegerField(default=0)),
                ('checked_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LinkCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2048)),
                ('status', models.CharField(choices=[('pending', '待检查'), ('running', '检查中'), ('success', '正常'), ('failed', '失效')], default='pending', max_length=16)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('action_status', models.CharField(choices=[('unhandled', '待处理'), ('ignored', '已忽略'), ('fixed', '已修复'), ('deleted', '已删除')], default='unhandled', max_length=16)),
                ('action_note', models.TextField(blank=True, null=True)),
                ('action_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_checks', to='core.Pin')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='linkcheck',
            index=models.Index(fields=['status', 'action_status'], name='core_linkch_status_b17423_idx'),
        ),
        migrations.AddIndex(
            model_name='linkcheck',
            index=models.Index(fields=['pin', 'created_at'], name='core_linkch_pin_id_cd414a_idx'),
        ),
    ]
