# Generated by Django 2.2.28 on 2026-06-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20260613_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkcheck',
            name='action_status',
            field=models.CharField(choices=[('unhandled', '待处理'), ('ignored', '已忽略'), ('fixed', '已修复'), ('deleted', '已删除'), ('handled', '已处理')], default='unhandled', max_length=16),
        ),
    ]
