# Generated by Django 2.2.28 on 2026-06-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20260613_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkcheck',
            name='error_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddIndex(
            model_name='linkcheck',
            index=models.Index(fields=['error_type'], name='core_linkch_error_t_c50b7d_idx'),
        ),
    ]
