# Generated by Django 2.2.28 on 2026-06-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20260613_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkchecktask',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='linkchecktask',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=16),
        ),
    ]
