# Generated by Django 2.2.28 on 2026-06-13 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20260613_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkcheck',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_checks', to='core.LinkCheckTask'),
        ),
        migrations.AddIndex(
            model_name='linkcheck',
            index=models.Index(fields=['task'], name='core_linkch_task_id_aefeef_idx'),
        ),
    ]
