# Generated by Django 5.2.13 on 2026-06-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_images', '0002_auto_20180826_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
